run: qvm.cpp \
     Parser.h Parser.cpp \
		 CodeWriter.h CodeWriter.cpp \
		 ParsePath.h ParsePath.cpp
	g++ qvm.cpp Parser.cpp CodeWriter.cpp ParsePath.cpp -o app

debug: qvm.cpp \
     Parser.h Parser.cpp \
		 CodeWriter.h CodeWriter.cpp \
		 ParsePath.h ParsePath.cpp
	g++ -g qvm.cpp Parser.cpp CodeWriter.cpp ParsePath.cpp -o app