run: qvm.cpp \
     Parser.h Parser.cpp \
		 CodeWriter.h CodeWriter.cpp
	g++ qvm.cpp Parser.cpp CodeWriter.cpp -o app

debug: qvm.cpp \
     Parser.h Parser.cpp \
		 CodeWriter.h CodeWriter.cpp
	g++ -g qvm.cpp Parser.cpp CodeWriter.cpp -o app