run: qCompiler.cpp \
     JackTokenizer.h JackTokenizer.cpp \
		 ParsePath.h ParsePath.cpp
	g++ qCompiler.cpp JackTokenizer.cpp ParsePath.cpp  -o app

debug: qCompiler.cpp \
     JackTokenizer.h JackTokenizer.cpp \
		 ParsePath.h ParsePath.cpp
	g++ -g qCompiler.cpp JackTokenizer.cpp ParsePath.cpp  -o app