run: qCompiler.cpp \
     JackTokenizer.h JackTokenizer.cpp \
		 ParsePath.h ParsePath.cpp \
		 CompilationEngine.h CompilationEngine.cpp 
	g++ qCompiler.cpp JackTokenizer.cpp ParsePath.cpp CompilationEngine.cpp  -o app

debug: qCompiler.cpp \
     JackTokenizer.h JackTokenizer.cpp \
		 ParsePath.h ParsePath.cpp \
		 CompilationEngine.h CompilationEngine.cpp 
	g++ -g qCompiler.cpp JackTokenizer.cpp ParsePath.cpp CompilationEngine.cpp  -o app