debug: main.cpp \
       code.h code.cpp \
			 Parser.h Parser.cpp \
			 SymbolTable.h SymbolTable.cpp
	g++ main.cpp code.cpp Parser.cpp SymbolTable.cpp -o app -DDEBUG

run: main.cpp \
       code.h code.cpp \
			 Parser.h Parser.cpp \
			 SymbolTable.h SymbolTable.cpp
	g++ main.cpp code.cpp Parser.cpp SymbolTable.cpp -o app
